### ISSUE TITLE
Change namespace name for the Networking module

### ISSUE THREAD

**Issue by Smile040501** [ishwargov/PlexShare#21]
@Mohammad-Umar-Sultan @BossLogic314 The namespace name for the networking module should be `PlexShareNetwork` as per the folder name.

**Comment by BossLogic314** [comment]
Done.

**Comment by BossLogic314** [comment]
> @Mohammad-Umar-Sultan @BossLogic314 The namespace name for the networking module should be `PlexShareNetwork` as per the folder name.

Done.

**Comment by ishwargov** [comment]
Pushed

**Comment by ishwargov** [comment]
Pushed
