### ISSUE TITLE
Screenshare view must be instantiated only once

### ISSUE THREAD

**Issue by dkodar20** [ishwargov/PlexShare#51]
https://github.com/ishwargov/PlexShare/blob/4bc72b192a378042ebe0664918d9c1c17474b640/src/PlexShareApp/MainScreenView.xaml.cs#L73-L74

Similar to how it is done for whiteboard, either of the `ScreenshareClientView` or `ScreenshareServerView` must be instantiated in an `if` condition and not both.

@kabraneel

**Comment by kabraneel** [comment]
Fixed (I think).
