### ISSUE TITLE
Build Failure due to Constructor being inaccessible

### ISSUE THREAD

**Issue by Smile040501** [ishwargov/PlexShare#54]
https://github.com/ishwargov/PlexShare/blob/79d681515d252484d213fea301fd7e1d98f790ef/src/PlexShareTests/WhiteboardTests/UndoRedoTests.cs#L19

@JerryJohnThomas

**Comment by naren-loganathan** [comment]
This has been commented out and pushed for now, Whiteboard is working on resolving this.
