### ISSUE TITLE
Emojis not supported due to encoding

### ISSUE THREAD

**Issue by Sughandhan** [ishwargov/PlexShare#75]
https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SendQueueListenerClient.cs#L88
https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SendQueueListenerServer.cs#L108
https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SocketListener.cs#L114-L115

Please replace the ASCII with UTF32 @BossLogic314
```c#
Encoding.ASCII --> Encoding.UTF32
```

**Comment by BossLogic314** [comment]
> https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SendQueueListenerClient.cs#L88
> 
> 
> https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SendQueueListenerServer.cs#L108
> 
> 
> https://github.com/ishwargov/PlexShare/blob/e9e1c4681b3febc0906a98534c6e2a615aa117f0/src/PlexShareNetwork/Sockets/SocketListener.cs#L114-L115
> 
> Please replace the ASCII with UTF32 @BossLogic314
> 
> ```cs
> Encoding.ASCII --> Encoding.UTF32
> ```

Done.
